### ISSUE TITLE
Hamburger menu not working as expected

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-skeleton-onepage-site#12]
Nice skeleteon/theme!
When I view it on my phone, het hamburgermenu only displays 1 entry: Home.
Can it be adapted that it displays all menu-items?

![start_2016-09-03_19-07-44](https://cloud.githubusercontent.com/assets/12153667/18226427/c99cc192-7209-11e6-9f5d-25670016d4ff.png)

**Comment by rhukster** [comment]
This is not a bug.. The menu items are 'on-page' menu items, and it makes no sense to display those in a side menu.  Any other regular pages will be displayed in the menu.  

A better option in this scenario is to turn off the side-menu completely by removing it, but it's there to allow for other pages to be added.

**Comment by rkammann** [comment]
I agree with awrog's view that the hamburger menu's default behaviour is problematic. The hamburger menu replaces a full menu of modular pages with a mere redundant duplication of the Home link. If indeed it made 'no sense' to display the modular pages in the hamburger menu, then surely the same assertion would have to apply to the regular non-hamburger navigation in the first place: it wouldn't make any sense either. 

In the hamburger menu, couldn't the modular page links be nested under the Home link, using indents to show their subsumption?
