### ISSUE TITLE
admin plugin breaks the site for this skeleton

### ISSUE THREAD

**Issue by pubmania** [getgrav/grav-skeleton-onepage-site#13]
The moment I install admin plugin site stops loading and admin I get the error

> Not Found
> The requested URL /grav/admin was not found on this server.

Without admin plugin the site loads just fine. With the plugin installed the url automatically appends admin and normal site URL is not even accessible.

**Comment by rhukster** [comment]
This is not a bug, you simply don't have page rewrites working - http://learn.getgrav.org/troubleshooting/page-not-found

**Comment by pubmania** [comment]
Thanks...yes you are right. I forgot to create the conf file specific to new folder and it was just using the default one.
