### ISSUE TITLE
Omitted page slugs in the One-Page Site skeleton: an issue?

### ISSUE THREAD

**Issue by rkammann** [getgrav/grav-skeleton-onepage-site#15]
In a site modeled on the One-Page Site skeleton, I get intermittent white-outs in which the site just disappears or returns an "Error 503 Backend fetch failed" message from the Varnish cache server instead of rendering a page. Checking the logs, I found this, and this only:

> [2017-02-08 09:05:50] grav.NOTICE: Invalid slug set in YAML frontmatter: /home/_philippe => _philippe [] []
[2017-02-08 09:08:06] grav.NOTICE: Invalid slug set in YAML frontmatter: /home/_philippe => _philippe [] []
[2017-02-08 09:17:47] grav.NOTICE: Invalid slug set in YAML frontmatter: /home/_kontakt => _kontakt [] []
[2017-02-08 09:23:20] grav.NOTICE: Invalid slug set in YAML frontmatter: /home/_service => _service [] []

In line with the example of the One-Page Site skeleton, none of my pages have a page slug set to begin with. Is this a possible defect of the skeleton, and is it reasonable to assume that the site outages could be caused by omitted page slugs?

**Comment by flaviocopes** [comment]
The `grav.NOTICE: Invalid slug set in YAML frontmatter` is a notice, so this is very unlikely to cause the  white page. Also, happens only when the page has a slug set in the header, and it's not respecting the format rules (a-Z0-9).

The white pages might be an environment issue, but not related to this notice.

**Comment by flaviocopes** [comment]
(closing as not strictly related to this skeleton, reopen on Grav core if needed)
