### ISSUE TITLE
No Menu Items on Mobile Devices except 'Home'

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-skeleton-onepage-site#5]
On mobile devices there is only a 'Home' menu item.
'Top', 'Highlights', 'Easy Content', 'Features' menu items are not shown.

**Comment by rhukster** [comment]
This is actually not an issue. The one-page-skeleton only has a 'home' page.  The items in the menu on the desktop view are just page anchors on the current page.  These would not really make sense in off canvas menu as you can just flick to scroll to them.

**Comment by axel-rank** [comment]
I think it makes sense to add navigation, especially if your articles are long.
There was the same issue in Photographer Theme and mobile navigation has been added.
Even in agency theme (which is a one page) there are all menu items displayed on mobile view.

**Comment by rhukster** [comment]
There are quite a few threads on the forum that go into how to do this yourself.  For example:

http://getgrav.org/forum#!/theme-development:grav-one-page-antimatter-th

**Comment by axel-rank** [comment]
Ok. I'm using agency and I like it. Thanks for the link.
