### ISSUE TITLE
_highlights page links are wrong

### ISSUE THREAD

**Issue by msharp1** [getgrav/grav-skeleton-onepage-site#8]
Hi,
The links in the sentence below:

```
We believe the best recipe to make something great, is to bake with [quality ingredients](#) and add dollops of [cool stuff](#). 
```

Both link to http://host/gravdir/home/_highlights which are 404.

Where I guess it should link to http://host/gravdir/#highlights (or #something) ?

**Comment by rhukster** [comment]
Fixed in develop: https://github.com/getgrav/grav/commit/f74562987dacd46290a7db6c6c4bc66b06c6cd8a
